### ISSUE TITLE
an error regarding prog_x_st

### ISSUE THREAD

**Issue by redskies421** [16EAGLE/moveVis#12]
Hello,

I absolutely love your work! However, I have been having some issues regarding creating and saving the gif and I was curious if you can give some insight.

Right, so...I tested out the package on a small section of the data set. Interestingly enough, it only displayed a portion of the data (although it did run successfully). Right, so I isolated the ones that didn't run and tried them on their own, however, unfortunately, it didn't work. Likewise, I tried another random sample and I got the same error message at the end which is the following: Error in prog_x_st[2:prog_bar_length] : 
  only 0's may be mixed with negative subscripts

The reason why I am confused is that it worked fine the first time and the data is formatted in the same exact way, nor did the animals move considerably. The only difference are the dates and (very minimally, of course) the coordinates (but not by more than a few kms). 

Do you know why it may have worked for one 'test run' but not the other? 

Thank you.

**Comment by 16EAGLE** [comment]
Thank you for your comment, The current version available on CRAN will be updates in a few days solving multiple issues, maybe including yours. Until then, try using the current github version:

```s
install.packages("devtools")
devtools::install_github("16EAGLE/moveVis")
library(moveVis)
```
If you rerun your code, do you still face the same problem? If it still does not work, please provide some more details, code/data example, otherwise its difficult to find the cause.

**Comment by 16EAGLE** [comment]
0.9.6 is on CRAN now. Please update and check, if the issue still exists: `install.packages("moveVis")`

**Comment by 16EAGLE** [comment]
Please reopen, if issue still exists.
