### ISSUE TITLE
possible speed improvements (doMC or similar, memory management)

### ISSUE THREAD

**Issue by vestlink** [16EAGLE/moveVis#16]
Would it be sensible to be able to do parallel computing while creating the animations?

**Comment by 16EAGLE** [comment]
Do you mean to run animate_move() without letting R to wait for it to finish?

Regarding internal parallel processing: I experimented with parallelizing the frame creation (most time-intensive) on an 8-core 2,7 GHz machine, using 7-cores, each creating a subset of the number of frames. I considered the speed improvements of not being high enough to justify the negative impact on the available performance while animate_move() had been running, which would have forced the user to stop using the system. Maybe one solution would be an argument of turning parallel processing on/off optionally...

**Comment by vestlink** [comment]
hmm. I see. Sounds like that there is not much to gain here then. Just a though.

**Comment by 16EAGLE** [comment]
Thanks for your ideas anyways!
I think so, also, because the duration of the frames creation and thereby most of the overall processing time is mostly depending on the disk's writing speed, since each frame is mapped to disk as PNG.

**Comment by vestlink** [comment]
Would in-memory cache help if you avoided the temporary on-disk write?

**Comment by 16EAGLE** [comment]
Yes. One way (which would be a lot of work) would be to rethink the frame generation itself and to not create and store each single rasterized frame, but to specify the specific pixels that change. This would reduce the needed memory space a lot. However, I have not approached this topic yet, since I would not have enough time for this kind of a rebuild currently, but am open for ideas.

With the current set-up of the package, it would make much more sense to store the frames in RAM to avoid losing time by i/o operations. However, for that, the user would need a lot of RAM depending on the size of the output video. A machine with 32 GB of RAM would have no problems with doing a medium-sized video using moveVis completely in-memory.

If there would be interests to have the option to use RAM only, I could implement it for users who want to create very short videos fastly or users not having memory resource limitations.

**Comment by vestlink** [comment]
It could be a useful for users with powerful machines.
