### ISSUE TITLE
Problem with base-map

### ISSUE THREAD

**Issue by stmarcin** [16EAGLE/moveVis#24]
Hi,
I am testing moveVis package to visualize GTFS (public transport) data. I have a problem with base map. I have created data.frame called `GTFS` and then I used this file to create move class object. Finally I executed a following code to get video output file:
 `animate_move(GTFS_ani, out_dir, out_name = "test5", conv_dir = conv_dir, 
             paths_mode = "true_data", frames_nmax = 10,
             img_caption = img_caption, img_title = img_title,
             log_level = 1, out_format = "mp4",
             map_type = "roadmap",
             paths_col = line_colors) `

I've got following response:

> Checking prerequisites...
Warning: Detected minimum temporal resolution of 42 seconds, but non-uniform timestamps, paths interpolation will be forced.
Warning: 'frames_tres' set to 42 seconds, since undefined.
Warning: Linear paths interpolation can massively distort movement, particularly non-movement periods!
Computing uniform frame times from timestamps...
Assigning base layers per frame ticks...
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=40.3871530746987,-3.66474108396037&zoom=9&size=494x500&maptype=satellite&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error: Download from Google failed. Please check your internet connection.

Any idea, how to solve this issue? 

Also: the above change my working directory:
before it used to be: 
`getwd()`
> "F:/Documentos/MSCA_CAlCULUS/TRAINING/MovieR"

While after the (unsuccessful) execution  of `animate_move`  I get this:
`getwd()`

> [1] "C:/Users/Marcin/AppData/Local/Temp/RtmpCGQzFJ/moveVis"

The same effect regardless internet connection nor system (I've tried on Windows 10 and macOS HighSierra (10.13.6). 

I apprreciate any help,
Marcin

**Comment by jayvonbank** [comment]
I am having this same issue for use within the last 12 hours as well...code worked fine yesterday evening and this morning I receive the same error no matter what modifications I make to the code.

**Comment by jayvonbank** [comment]
Just tried the animate_move() function again today with the exact same properties and data set as yesterday, and it appears to be working properly.  Must have been a temporary issue with Google?

**Comment by sarahefischer** [comment]
I'm having the same issue today, and the code works after running it ~4 times (without changing anything). Strange!

**Comment by darnold10** [comment]
So I have been having the same issue with the API key. I had previously signed up for an API key and this had fixed the problem. 
My code is as follows:

x <- c('move', 'moveVis', 'ggmap')
sapply(x, library, character = TRUE)

#Assigning personal API code
register_google(key = "MY PERSONAL API CODE")

#Assign lynx to this dataframe
LYNX <- lynx.1

#Turn the lynx dataframe into a move class object
m <- move(LYNX$Long, LYNX$Lat, proj=CRS("+proj=longlat +ellps=WGS84"), time = LYNX$Time,
          animal=LYNX$ID, data=LYNX)

#Assigning Essential Objects
conv_dir <- get_libraries()
out_dir <- paste0(getwd())

#Run a 200 frame animation test
animate_move(m, out_dir, conv_dir,
             tail_elements = 10,
             map_type = 'satellite',
             log_level = 1,
             frames_fps = 20,
             frames_tres = 2000,
             extent_factor = 0.0001,
             frames_nmax = 200,
             out_name = 'Wiseman12',
             out_format = "mp4")

This code is still giving me the error message that everyone else on the thread is getting. The odd part is that in ggmap I can still manage to use get_map() to download a map and plot my data using ggplot. It makes me think that there is something about the way this package is using get_map that isn't allowing it to use my api key. Any thoughts?

This is the error message I'm getting...

Checking prerequisites...
Paths interpolation will be applied, since 'frames_tres' is user-defined.
Computing uniform frame times from timestamps...
Assigning base layers per frame ticks...
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error in download.file(gurl, filename, mode = "wb", quiet = TRUE) : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1'
In addition: Warning message:
In download.file(gurl, filename, mode = "wb", quiet = TRUE) :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=67.1287824006603,-150.43088554677&zoom=11&size=496x500&maptype=terrain&format=gif&sensor=false&scale=1': HTTP status was '403 Forbidden'
Error: Download from Google failed. Please check your internet connection.

**Comment by ctlamb** [comment]
Any updates on this? I'm a new moveVis user and the package doesn't seem to be working atm. Tried the API key addition as @darnold10 did. This fixes all my ggmap issues but not moveVis

**Comment by mattress25** [comment]
Is it possible to get this working in the meantime, say, without using a basemap?

**Comment by 16EAGLE** [comment]
Still had no time to fix the Google Maps issue. Will do next week.
moveVis is still usable without using a Google basemap, just by providing your own custom background layer(s). See the `layer` argument in the `animate_move()` documentation (http://movevis.org/reference/animate_move.html) and the part "Use your own basemap by adding lists of rasters and of timestamps" in the examples (http://movevis.org/reference/animate_move.html#examples).

**Comment by jlaufenb** [comment]
Beware of recommending users download and cache a Google map for later use. [Google API Terms of Service](https://cloud.google.com/maps-platform/terms/#3-license) restrict that type of use.  See also at the bottom of page [here](https://developers.google.com/maps/documentation/geolocation/policies).

**Comment by wlphipps** [comment]
Hi, this still seems to be an ongoing issue. Does anyone have any other fixes yet? 
Thanks

**Comment by darnold10** [comment]
For those of us that aren't able to make this work, I did find out that there is another animation type package similar to this one called anipaths. Seems to work pretty well as an alternative although it isn't quite as good as moveVis has been

**Comment by clairemason** [comment]
Hello @darnold10 @wlphipps @16EAGLE 

I just gave anipaths a go. @darnold10 did you have success using this one? I had a similar looking error message to moveVis with a **_HTTP status was '403 Forbidden'_** ... not sure whether it is related or not?? Let me know .. might be something else! I haven't investigated too deeply yet. 

Cheers 
Claire

**Comment by ctlamb** [comment]
Anipaths has worked well for me as an alternative. You need to supply an API via ggmap's register_google()

**Comment by clairemason** [comment]
Thank you @ctlamb Really appreciate the reply. Will give it a go!

**Comment by 16EAGLE** [comment]
Thank you all for reporting this issue. The issue should now be resolved (see commit 8f6e342), as the following changes have been made:
- For thematic maps, moveVis now uses OpenStreetMaps, which is freely and openly available. New map types have been added.
- For satellite/hybrid imagery, moveVis now uses high resolution besmaps form Microsoft Bing Maps. If you use moveVis very often, consider getting a free API key for the Bing Maps services by registering at Microsoft.
- For now, Google Maps basemaps have been removed, as I am working on a natively implemented Google Maps client. Google Maps basemaps options will be added in the next update, but will require a Google registration due to Google newly introduced data policies. The user will then be able to choose from Google or Microsoft products for satellite imagery, which, in my opinion, does not make much of a difference regarding basemap quality and is more a decision governed by the question where you want to be registered and tracked.
Please see http://movevis.org/news/index.html#movevis-0-9-9 for further details.

**Comment by wlphipps** [comment]
Excellent, thanks so much, I can confirm this is now working with the OSM maps - roadmap and hybrid. They aren't quite as visually attractive as the Google maps, but still great.
I assume map_type options are still "roadmap", "satellite", "hybrid" or "terrain", with no additional alternatives?
Thanks so much for developing this package, it is great for analysis and sci-comm.

**Comment by 16EAGLE** [comment]
Thank you. That's interesting, could you please provide me the output of sp::bbox(your_move_object), so that I can check the offset issue that you're describing?

map_type options now are  "satellite" (default), "hybrid", "roadmap", "roadmap_dark", "roadmap_bw", "roadmap_watercolor".

**Comment by wlphipps** [comment]
Thanks for the map_type options.

This is the output for sp::bbox(data_ani):
Error in sp::bbox(data_ani) : object not a >= 2-column array

So I checked the CRS and it returns as NA. Could this be the problem? It works with roadmap though. 

Code to create the move object as follows: 
data_ani <- split(move(mydata$lon, mydata$lat, proj=CRS("+proj=longlat +ellps=WGS84"), time = mydata$dt, animal=mydata$individual, data=mydata))
crs(data_ani) #check CRS
[1] NA

Do I need to assign a CRS to the move object? 

Thanks

**Comment by 16EAGLE** [comment]
Probably found the offset issue that you were referring to and hopefully fixed it. Could you reinstall moveVis and rerun your code to confirm if the basemap is now displayed correctly without offset?

**Comment by 16EAGLE** [comment]
Good to know, thanks for pointing that out. I will check the resolution issue. Google Maps will be implemented again soon in addition, with registration required. Wanted to implement a solution not completely requiring registration first.

**Comment by 16EAGLE** [comment]
> One comment on the outputs compared to previous versions with Google: the resolution is not as high, resulting in slightly blurred imagery and labels. This is the case for roadmap and hybrid outputs.

You can now use `map_zoom` to define level of detail in static basemaps (see documentation of `animate_move`: http://movevis.org/reference/animate_move.html). In addition, altering the overall size of your animation through `frames_height` and `frames_width` affects the size of the downloaded basemap.

**Comment by 16EAGLE** [comment]
solved with 657f08eed59fcb3aa8ba80191d09e36bb82666f6
