### ISSUE TITLE
Error -  incorrect number of layer names

### ISSUE THREAD

**Issue by mattress25** [16EAGLE/moveVis#28]
I am having issues running the movevis example data. I've run this example code previously before the latest update and it worked fine, but no longer. 

Heres the code I am running:

data("move_data")

move_data$dt <- as.POSIXct(strptime(move_data$dt, "%Y-%m-%d %H:%M:%S", tz = "UTC"))

data_ani <- split(move(move_data$lon, move_data$lat, proj=CRS("+proj=longlat +ellps=WGS84"),
                       time = move_data$dt, animal=move_data$individual, data=move_data))

#Specify output directory
out_dir <- paste0(getwd(),"")

#Specify some optional appearance variables
img_title <- "Movement of the white stork population at Lake Constance, Germany"
img_sub <- paste0("including individuals ")
img_caption <- "Projection: Geographical, WGS84; Sources: Movebank 2013; Google Maps"

animate_move(data_ani, 
             out_dir, 
             conv_dir = conv_dir, 
             tail_elements = 10,
             paths_mode = "true_data", 
             frames_nmax = 50,
             img_caption = img_caption,
             img_title = img_title,
             img_sub = img_sub, 
             log_level = 1, 
             out_format = "gif")

And I get this error: 

Error in `names<-`(`*tmp*`, value = c("red", "green", "blue")) : 
  incorrect number of layer names

Any help would be greatly appreciated!
Thanks,
Matt.

**Comment by kprz** [comment]
I have the same error using the example provided by the author of the package.

**Comment by animobu** [comment]
Hi, I am having the same issue. Has anyone found the solution for this?
Thanks!

**Comment by 16EAGLE** [comment]
Sorry for the late reply. This issue should be solved with the latest version of moveVis (0.10.0), which is on GitHub now. Please note that moveVis has been rewritten with version 0.10.0 to make it more flexible. Thus, code written for older versions will not work, since `animate_move` has been replaced by `align_move`, `frames_spatial` and `animate_frames`. See the examples in the `README` and on [movevis.org](http://movevis.org) for details on how to use the new syntax.

Please let me know if you encounter any problems.
