### ISSUE TITLE
NA timestamps

### ISSUE THREAD

**Issue by t-murray** [16EAGLE/moveVis#5]
After running the lines of code below, I keep getting an "Error in validity: There are NA timestamps records". The layout of my data is exactly the same as to move_data. I'm not sure what the error could be?

> for(i in 1:length(indi_subset)){
+   if(i == 1){
+     data_ani <- list(move(x=indi_subset[[i]]$lon,y=indi_subset[[i]]$lat,
+                           time=indi_subset[[i]]$dt,
+                           proj=CRS("+proj=longlat +ellps=WGS84"),
+                           animal=indi_levels[i]))
+   }else{
+     data_ani[i] <- list(move(x=indi_subset[[i]]$lon,y=indi_subset[[i]]$lat,
+                              time=indi_subset[[i]]$dt,
+                              proj=CRS("+proj=longlat +ellps=WGS84"),
+                              animal=indi_levels[i]))}
+ }
Error in validityMethod(as(object, superClass)) : 
  There are NA timestamps records

**Comment by 16EAGLE** [comment]
Thanks for the information, I am trying to find out, what the problem is here. Could you print out your timestamps and send them here? In case that the dataset you are using is freely available, it would be nice if you send it to me, so that I could reproduce the error. Have you already checked if there are timestamp records that do not fit the POSIXct format?

**Comment by t-murray** [comment]
Thanks for the reply. I've now attached my dataset. What appears to happen post POSIXct step is my date times disappear - this explains the timestamp error.

[RTalgoa2.txt](https://github.com/16EAGLE/moveVis/files/1111324/RTalgoa2.txt)

**Comment by t-murray** [comment]
I've managed to locate the error - thanks so much. The code works 100% up until the animate_move line where it can't make the link to my output directory. I have specified my output directory, but am still getting this error:

#Specify output directory
out_dir <- "c:/Users/t.murray/My Documents/Uni work/Post-doctoral studies/R CODE/AniMove/output"

Warning messages:
1: In file.remove("out_gif1.gif") :
  cannot remove file 'out_gif1.gif', reason 'No such file or directory'
2: In file.remove(paste0(out_name, ".gif")) :
  cannot remove file 'final_gif.gif', reason 'No such file or directory'
> 

It seems to be linking to a temporary file on my computer?

**Comment by 16EAGLE** [comment]
Thanks for your message here and on twitter. I tried to allocate the error. It seems that animate_move is unable to call  convert.exe. There is a bug in the get_imconvert() function which could be the reason for that.  Have you installed ImageMagick using get_imconvert() or have you done that manually? Can you please check the following: 
Go to your Program Files folder and there to the ImageMagick installation folder. Look there if there is a convert.exe file in the main directory. 

If there is no convert.exe, you can try the following workaround:
Download the portable ImageMagick version from ftp://ftp.imagemagick.org/pub/ImageMagick/binaries/ImageMagick-7.0.6-0-portable-Q16-x64.zip (64bit) or ftp://ftp.imagemagick.org/pub/ImageMagick/binaries/ImageMagick-7.0.6-0-portable-Q16-x86.zip (32bit) and unzip it to a directory of your choice. Then provide the path to the convert.exe in the main directory of the unzipped folder to the convert argument of animate_move. 

Otherwise, you can also reinstall an ImageMagick version that has the convert.exe included (there are versions without, which do not work with moveVis).

Please report me if that works out.

**Comment by t-murray** [comment]
Thanks so much for the reply. This is exactly what was happening. I uninstalled the old version of ImageMagik and and reinstalled the portable version as you suggested, unzipping it into my directory of choice. 

I'm happy to report that it works! Thank you so so much. The next step is to use the true_data portion of the code - this is ultimately what I am after.

Many thanks again. This is a great package.

**Comment by 16EAGLE** [comment]
Thank you! Glad to read that it works now!
