### ISSUE TITLE
Problems adding remote sensing data to penguin animation

### ISSUE THREAD

**Issue by jazelouled** [16EAGLE/moveVis#77]
Good morning,

I am trying to set up a background map for my animation with information about the chlorophyll concentration in the ocean. I have been able to create normal animations with an osm map but I cannot proceed with the remote sensing data. 

I have downloaded two files with chl data for two different days and stored them in a list (r_list). However, when it turns to run frames_spatial, I get the error: 

 "Error: Projections of 'm' and 'r_list' differ."

I have tried with compareCRS(m, r_list), and it returns "FALSE", but however, when I set the projection using: 
 
projection(r_list)<-"+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

and 

move_data<-df2move(dflatlon2018, proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0", x="lon", y="lat", time="time2", track_id = "nest")

it is exactly the same.  I don't know if it can have any relationship with the different extent of the chlorophyll raster and the move_data object. 

Sorry if it is not the right format to present and explain things around here. It is my first time!

Thank you so much!

**Comment by 16EAGLE** [comment]
Hi, two questions: 

- With `projection(xyz)<-`, you assign a projection without reprojecting. Just for clearity: Do you want to reproject your data (then you should use `projectRaster()` and `spTransform()`) or do you know for sure that your data represents the projection that you assign and you want to assign it since its missing?
- If `r_list` is a list, assigning a projection to the list itself will not work, since the raster elements of the list contain the `CRS`, not the list. You should reproject or assign projections for the elements of the list individually, instead.

If you want, you can share your data/subsets of it, then I can check what is wrong

**Comment by jazelouled** [comment]
Hi, 

Thanks a lot for your time. Here I attach you a zip file with a  subset of my tracking data and two nc files that i am trying to use as environmental layers. I also attach the code that I am using. 

[DATA_ANIMATION_PENGUINS_JAZEL.zip](https://github.com/16EAGLE/moveVis/files/3811759/DATA_ANIMATION_PENGUINS_JAZEL.zip)


Cheers!!

Jazel

**Comment by 16EAGLE** [comment]
Hi, sorry for my late reply. The issue simply is that you wrote `r_list = "r_list"` instead of `r_list = r_list`. Instead of a character, you want to pass your list of rasters. In addition, you need to define `r_times` so that `moveVis` knows the temporal positions of the rasters in `r_list`, like this (with the real dates of course):

```R
# some made-up raster dates
r_times <- as.POSIXct(c("2018-10-27 20:00:00", "2018-10-29 01:00:00"))

frames <- frames_spatial(m, r_list = r_list, r_times = r_times, fade_raster = F)
```
Hope this is still helpful after such a long time.

**Comment by 16EAGLE** [comment]
please reopen if the issue persists.
