### ISSUE TITLE
trace_show=TRUE discontinuities

### ISSUE THREAD

**Issue by spluque** [16EAGLE/moveVis#81]
In the latest release (0.10.3), the trace shows discontinuities, i.e. the default white path trace has gaps.  I'm unsure in what version this happened, but it's not there. Easily seen by running the example https://gist.github.com/16EAGLE/de21779c75aec8be27013f99dc311073

**Comment by 16EAGLE** [comment]
Thanks for notifying. This bug was accidentally introduced with the current CRAN version 0.10.3 and was fixed with commit bf66d30c1233c5995812ade42b98f657195831b5. I will soon push these changes to CRAN with version 0.10.4. Until then, please install 0.10.4 from GitHub using `remotes::install_github("16EAGLE/moveVis")` to remove the problem.

**Comment by 16EAGLE** [comment]
moveVis 0.10.4 has been released on CRAN - the issue should be fixed there now as well.
