### ISSUE TITLE
Error when crossing -180/180 longitude

### ISSUE THREAD

**Issue by johnsonamy24** [16EAGLE/moveVis#82]
Hello, 

I am working with my data (Lat Lon format) and my animal crosses the -180/180 degree line. I get an error with:

frames <- frames_spatial(m, trace_show = TRUE, equidistant = FALSE,
                         map_service = "osm", map_type = "terrain_bg")
>>  Error in .local(x, ...) : col <= x@ncols is not TRUE

Or if I use a subset, sometimes that works but then I get an error with:
frames <- frames %>% add_labels(title = "test", caption = "test", 
                                x = "Longitude", y = "Latitude") %>%
  add_timestamps(type = "label") %>% 
  add_progress(colour = "white") %>%
  add_northarrow(colour = "white", position = "bottomleft") %>% 
  add_scalebar(colour = "black", position = "bottomright",
               distance = 600)
>> Warning message: In .pointsToMatrix(p2) : longitude > 180

If I run the code with just the locations before crossing the 180 line, it works. If I run the code with just the data after the 180 line, it works. If I run the code where the animal crosses the line, it doesn't work. 

I've attached a sample of the data where the crossing occurs. Thanks for any help.

[sampledata.txt](https://github.com/16EAGLE/moveVis/files/4273031/sampledata.txt)

**Comment by 16EAGLE** [comment]
Hi,

since this has been an issue to others too, I will work on implementing a solution for displaying tracks in a geographical coordinate system that cross the dateline. 

However, generally it might be worth thinking about using an appropriate projection given the very high latitudes (and the dateline crossing) that you are dealing with. For example, use an azimuthal stereographic projection (https://proj.org/operations/projections/stere.html) or others.

Rough example with `stere` (maybe change orientation so that north is top):

```R
library(moveVis)
df <- read.csv("sampledata.txt", sep = "\t")
df$timestamp <- as.POSIXct(df$timestamp)

# convert and align
m <- df2move(df, proj = "+proj=longlat +datum=WGS84 +no_defs", x = "location.long", y = "location.lat", time = "timestamp", track_id = "name")
m <- align_move(m, 24, unit = "hours")

# reproject
m <- sp::spTransform(m, sp::CRS("+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"))

frames <- frames_spatial(m, trace_show = TRUE, equidistant = FALSE,
                         map_service = "osm", map_type = "terrain_bg")
frames[[99]]
```


![plot_zoom_png](https://user-images.githubusercontent.com/23257860/75703753-61a28480-5cb8-11ea-8a4a-a057ce14116f.png)

I'll let you know here as soon as I have a proper solution for dateline crossing in an unprojected CRS.

**Comment by 16EAGLE** [comment]
I just added a handling of dateline crossings of unprojected tracks (geographic CRS, lat/lon) with commit d40324c8 (fixing #75). You can use the newly added argument `cross_dateline` of `frames_spatial` to force `moveVis` to extend frames and connect tracks across the dateline instead of clipping frames at longitudes -180 and 180. Frames are expanded towards the side of the dateline that is smaller in space.

Here is a short example with your sample data:

```R
library(moveVis)
df <- read.csv("sampledata.txt", sep = "\t")
df$timestamp <- as.POSIXct(df$timestamp)

m <- df2move(df, proj = "+proj=longlat +datum=WGS84 +no_defs", x = "location.long", y = "location.lat", time = "timestamp", track_id = "name")
m <- align_move(m, 24, unit = "hours")

frames <- frames_spatial(m, cross_dateline = TRUE,
                         trace_show = TRUE, map_service = "osm", map_type = "terrain") %>% 
  add_gg(gg = expr(theme(aspect.ratio = 0.5))) # stretching the y axis a bit

frames[[99]]
```

![plot_zoom_png](https://user-images.githubusercontent.com/23257860/75803003-fcb16200-5d7d-11ea-8cd2-640efcd8a787.png)

Regarding your questions that you sent via e-mail:

**Fuzziness of basemaps**: The fuzziness is a result of reprojecting. All basemaps are originally projected as Web Mercator. If you use Web Mercator, basemaps are not reprojected and thus appear as delivered from the respective map service (see the last paragraph of http://movevis.org/articles/example-1.html for an example on this). The rotation of your map depends on the projection, in case of stere you can change the PROJ arguments to alter the orientation of the projection.

**Adding lat/lon to projected maps**: Yes, you can do this by using `ggplot2`/`sf` with `add_gg`. Here an example with `stere` + lat/lon graticules:

```R
library(moveVis)
library(ggplot2)
df <- read.csv("moveVIS_all_oneaday.csv")
df$timestamp <- as.POSIXct(df$timestamp)

m <- df2move(df, proj = "+proj=longlat +datum=WGS84 +no_defs", x = "location.long", y = "location.lat", time = "timestamp", track_id = "name")
m <- align_move(m, 24, unit = "hours")
m <- sp::spTransform(m, sp::CRS("+init=epsg:3995"))

frames <- frames_spatial(m, trace_show = TRUE, map_service = "osm", map_type = "terrain")
frames[[99]]
```
![Rplot](https://user-images.githubusercontent.com/23257860/75804198-e86e6480-5d7f-11ea-8f0e-4d166c16738a.png)

```R
# adding lat/lon graticules with add_gg and ggplot2
frames <- frames %>% 
  add_gg(gg = expr(ggplot2::coord_sf(crs = sf::st_crs(3995), datum = sf::st_crs(4326), clip = "on", expand = F))) %>% 
  add_gg(gg = expr(theme(panel.background = element_rect(fill = NA), panel.ontop = TRUE)))
frames[[99]]
```
![Rplot01](https://user-images.githubusercontent.com/23257860/75804222-f02e0900-5d7f-11ea-8585-2edb17129582.png)

**Comment by JoChambon** [comment]
Hi,

There seems to still be issues with the dateline crossing. I tried to animate the track from one animal that crosses the dateline but received a warning message that the argument 'cross_dateline' was ignored due to CRS specification, but as far as I am aware of the CRS I specified is unprojected/geographical.

```
move_data <- df2move(df=data_sub_2,proj="+proj=longlat +datum=WGS84",x="lon",y="lat",time="timestamp") #track from only one animal
m <- align_move(move_data, res = 15, unit = "mins") #tracking resolution of 15mins
frames <- frames_spatial(m, cross_dateline = TRUE) #track crossing the dateline

Warning: Argument 'cross_dateline' is ignored, since the coordinate reference system of 'm' is not geographical (long/lat).
Checking temporal alignment...
Processing movement data...
Approximated animation duration: ≈ 175.28s (~2.92 minutes) at 25 fps for 4382 frames
Retrieving and compositing basemap imagery...
 |============================================================================================================================| 100% elapsed=00s  
Error in .local(x, values, ...) : the size of 'values' is not correct
```

Any idea where the issue might come from?

Cheers

Jo
